import io
import os
import re
import urllib.request
import logging
import asyncio
import tempfile
import subprocess
from typing import Any, Dict, List
import pypdf
import pdfplumber
import pypdfium2 as pdfium
from pptx import Presentation
from google import genai
from google.genai import types

logger = logging.getLogger("board-simulator.tools")

def get_genai_client() -> genai.Client:
    project_id = os.environ.get("GOOGLE_CLOUD_PROJECT")
    location = os.environ.get("GOOGLE_CLOUD_LOCATION", "global")
    return genai.Client(vertexai=True, location=location)

def download_gcs_file(gcs_path: str) -> bytes:
    import google.auth
    from google.cloud import storage
    
    match = re.match(r"gs://([^/]+)/(.*)", gcs_path)
    if not match:
        raise ValueError(f"Invalid GCS path: {gcs_path}")
        
    bucket_name, blob_name = match.groups()
    _, project = google.auth.default()
    storage_client = storage.Client(project=project)
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(blob_name)
    
    logger.info(f"Downloading file from GCS: {gcs_path}")
    return blob.download_as_bytes()

def download_google_slides_as_pdf(slides_url: str) -> bytes:
    match = re.search(r"https://docs\.google\.com/presentation/d/([a-zA-Z0-9_-]+)", slides_url)
    if not match:
        raise ValueError(f"Invalid Google Slides URL: {slides_url}")
    presentation_id = match.group(1)
    export_url = f"https://docs.google.com/presentation/d/{presentation_id}/export/pdf"
    
    logger.info(f"Downloading Google Slides as PDF from: {export_url}")
    req = urllib.request.Request(
        export_url,
        headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    )
    with urllib.request.urlopen(req) as response:
        content_type = response.headers.get("Content-Type", "")
        if "application/pdf" not in content_type:
            raise ValueError(
                f"Failed to download Google Slides as PDF. Content-Type was '{content_type}'. "
                "Ensure the presentation is shared with 'Anyone with the link' or is public."
            )
        return response.read()

def convert_pptx_to_pdf_libreoffice(pptx_bytes: bytes) -> bytes:
    logger.info("Attempting to convert PPTX to PDF using LibreOffice...")
    with tempfile.TemporaryDirectory() as temp_dir:
        input_path = os.path.join(temp_dir, "input.pptx")
        with open(input_path, "wb") as f:
            f.write(pptx_bytes)
        
        # Headless command for soffice/libreoffice
        cmd = ["soffice", "--headless", "--convert-to", "pdf", "--outdir", temp_dir, input_path]
        try:
            subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
            output_pdf_path = os.path.join(temp_dir, "input.pdf")
            if os.path.exists(output_pdf_path):
                with open(output_pdf_path, "rb") as f:
                    return f.read()
        except Exception as e:
            logger.warning(f"soffice conversion failed: {e}. Trying libreoffice...")
            cmd[0] = "libreoffice"
            try:
                subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
                output_pdf_path = os.path.join(temp_dir, "input.pdf")
                if os.path.exists(output_pdf_path):
                    with open(output_pdf_path, "rb") as f:
                        return f.read()
            except Exception as ex:
                raise RuntimeError(f"LibreOffice conversion failed: {ex}")
    raise FileNotFoundError("Converted PDF was not generated by LibreOffice.")

def extract_pptx_text(file_bytes: bytes) -> str:
    prs = Presentation(io.BytesIO(file_bytes))
    extracted_slides = []
    
    for idx, slide in enumerate(prs.slides):
        slide_text = []
        slide_text.append(f"=== SLIDE {idx+1} ===")
        for shape in slide.shapes:
            if hasattr(shape, "text") and shape.text:
                slide_text.append(shape.text.strip())
            if shape.has_table:
                table_rows = []
                for row in shape.table.rows:
                    row_cells = [cell.text.strip() for cell in row.cells if cell.text]
                    if row_cells:
                        table_rows.append(" | ".join(row_cells))
                if table_rows:
                    slide_text.append("\n".join(table_rows))
        extracted_slides.append("\n".join(slide_text))
        
    return "\n\n".join(extracted_slides)

async def run_vision_ocr(client: genai.Client, img_bytes: bytes, page_idx: int) -> tuple[int, str]:
    prompt = (
        "This is a page image from a board paper. It contains very little native text "
        "and might represent a slide, table, chart, or diagram. "
        "Please extract all textual and tabular data from this page image and format it as "
        "clean Markdown text. If it is a table or list, format it as a clean Markdown table "
        "or list. Do not include decorative background text, page numbers, or logos."
    )
    try:
        response = await client.aio.models.generate_content(
            model="gemini-3.5-flash",
            contents=[
                types.Part.from_bytes(data=img_bytes, mime_type="image/jpeg"),
                prompt
            ]
        )
        return page_idx, response.text or ""
    except Exception as e:
        logger.error(f"Vision OCR failed on Page {page_idx}: {e}")
        return page_idx, ""

async def run_vision_ocr_sem(sem: asyncio.Semaphore, client: genai.Client, img_bytes: bytes, page_idx: int) -> tuple[int, str]:
    async with sem:
        return await run_vision_ocr(client, img_bytes, page_idx)

async def extract_pdf_text_hybrid_async(file_bytes: bytes) -> str:
    pdf_file = io.BytesIO(file_bytes)
    reader = pypdf.PdfReader(pdf_file)
    doc_pages = []
    for idx, page in enumerate(reader.pages):
        text = page.extract_text() or ""
        doc_pages.append(f"=== PAGE {idx+1} ===\n{text.strip()}")
    return "\n\n".join(doc_pages)

async def extract_board_paper_async(file_path: str = "", file_bytes: bytes = None, filename: str = "") -> Dict[str, Any]:
    logger.info(f"Starting extraction for board paper: {file_path or filename}")
    try:
        # Detect if file_path is a Google Slides URL
        is_google_slides_url = False
        if file_path and ("docs.google.com/presentation" in file_path or "docs.google.com/slides" in file_path):
            is_google_slides_url = True
            
        if not file_bytes:
            if is_google_slides_url:
                try:
                    file_bytes = download_google_slides_as_pdf(file_path)
                    filename = "google_slides.pdf"
                except Exception as e:
                    return {
                        "status": "error",
                        "message": f"Failed to download Google Slides presentation: {e}"
                    }
            elif file_path.startswith("gs://"):
                file_bytes = download_gcs_file(file_path)
                filename = file_path.split("/")[-1]
            else:
                if not os.path.exists(file_path):
                    return {
                        "status": "error",
                        "message": f"File path {file_path} does not exist."
                    }
                with open(file_path, "rb") as f:
                    file_bytes = f.read()
                filename = os.path.basename(file_path)
            
        file_ext = filename.split(".")[-1].lower()
        
        if file_ext == "pdf":
            extracted_text = await extract_pdf_text_hybrid_async(file_bytes)
            file_type = "pdf"
        elif file_ext in ["pptx", "ppt"]:
            # Try to convert PPTX to PDF using LibreOffice for high-fidelity Vision OCR
            try:
                pdf_bytes = convert_pptx_to_pdf_libreoffice(file_bytes)
                extracted_text = await extract_pdf_text_hybrid_async(pdf_bytes)
                file_type = "pdf"
            except Exception as e:
                logger.warning(
                    f"LibreOffice conversion failed: {e}. "
                    "Falling back to native PPTX shape text extraction..."
                )
                extracted_text = extract_pptx_text(file_bytes)
                file_type = "pptx"
        else:
            return {
                "status": "error",
                "message": f"Unsupported file extension: .{file_ext}. Only PDF and PPTX are supported."
            }
            
        return {
            "status": "success",
            "file_type": file_type,
            "text": extracted_text
        }
    except Exception as e:
        logger.exception(f"Failed to extract board paper: {e}")
        return {
            "status": "error",
            "message": str(e)
        }

def search_member_news(name: str, query: str) -> Dict[str, Any]:
    search_query = f"{name} Woolworths board {query}"
    logger.info(f"Running web grounding search: '{search_query}'")
    
    fallback_database = {
        "Scott Perkins": [
            "Scott Perkins advocates for strategic clarity and values customer trust. Rebuilding trust is a major focus.",
            "Perkins emphasised the recent CEO transition was independent and orderly.",
            "Dual roles as chair of Woolworths and Origin Energy provide perspectives on decarbonisation, ESG, and public scrutiny."
        ],
        "Amanda Bardwell": [
            "Amanda Bardwell, architect of WooliesX, champions e-commerce, loyalty, and digital innovation.",
            "Bardwell notes online grocery margins are thinner, emphasising operational efficiency to improve profitability.",
            "She is highly customer-focused and values data-driven decision making."
        ],
        "Maxine Brenner": [
            "Maxine Brenner is a veteran director focusing heavily on risk, sustainability, and regulatory compliance.",
            "Navigated reputational risk and public trust recovery from her past roles (including Qantas and Telstra).",
            "Brenner applies a legal and regulatory lens to corporate strategy and capital allocation."
        ],
        "Jennifer Carr-Smith": [
            "Jennifer Carr-Smith brings hands-on experience in online grocery delivery (former CEO of Peapod).",
            "She is pragmatic about thin e-commerce margins and the logistics of fresh food fulfillment.",
            "Carr-Smith strongly supports digital transformation and sustainable sourcing models."
        ],
        "Philip Chronican": [
            "Philip Chronican focuses heavily on culture, ethics, and accountability on the board.",
            "Guided NAB through building public trust after the financial services Royal Commission.",
            "He is known for financial and risk prudence, urging the board to 'never make a promise you can't keep'."
        ],
        "Kathee Tesija": [
            "Kathee Tesija brings mass-market merchandising and supply chain expertise from Target US.",
            "She focuses on store layout integration, private label development, and global product sourcing.",
            "Tesija supports omnichannel scaling and inventory optimisation."
        ],
        "Warwick Bray": [
            "Warwick Bray brings strict financial discipline (former Telstra CFO) to technology and capital investment ROI.",
            "He heavily scrutinises digital projects for financial viability and performance metrics.",
            "Bray supports data-democratisation inside organisations to improve agility."
        ],
        "Ken Meyer": [
            "Ken Meyer brings deep operational food retail expertise from Whole Foods Market (EVP of Operations).",
            "He focuses on fresh food excellence, quality-led differentiation, and collaborative supplier relationships.",
            "Meyer strongly supports ESG initiatives and purpose-driven capitalism."
        ],
        "Jon Alferness": [
            "Jon Alferness brings Silicon Valley product discipline and generative AI leadership from Walmart US and Google.",
            "He advocates for a 'people-led, tech-enabled' approach, supporting front-line staff with tech enablement.",
            "Alferness strongly pushes for retail AI deployment, digital search, and integrated omnichannel networks."
        ]
    }
    
    matching_results = []
    for key_name, stances in fallback_database.items():
        if key_name.lower() in name.lower():
            matching_results = stances
            break
            
    if not matching_results:
        matching_results = [
            f"{name} is a Director at Woolworths Group focusing on traditional retail operations and corporate governance.",
            f"News shows {name} supports balanced stakeholder consideration, pricing value, and risk compliance.",
            f"{name} participates in board-level strategy meetings in 2025/2026."
        ]
        
    return {
        "status": "success",
        "query": search_query,
        "results": matching_results
    }
